name: GitHub Actions Demo
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Verify Ubuntu Version."
      - run: lsb_release -a
